### ISSUE TITLE
在安装simpleCV时出现报错

### ISSUE THREAD

**Issue by wangk98** [Z-Zheng/FreeNet#3]
您好，我在终端安装simpleCV时出现了以下报错:
ERROR: Could not find a version that satisfies the requirement tensorboardX==1.7 (from simplecv) (from versions: none)
ERROR: No matching distribution found for tensorboardX==1.7
请问您知道如何解决吗，simpleCV是基于tensorflow框架的吗，但freenet好像是基于pytorch，很抱歉打扰您

**Comment by Z-Zheng** [comment]
SimpleCV是基于pytorch的
可以尝试先把tensorboardX先安装好再装SimpleCV

**Comment by wangk98** [comment]
运行train.py出现如下报错，请问是tensorboardx的问题吗
Traceback (most recent call last):
  File "D:\code\FreeNet-master\train.py", line 62, in <module>
    train.run(config_path=args.config_path,
  File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\dp_train.py", line 29, in run
    cfg = config.import_config(config_path)
  File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\util\config.py", line 5, in import_config
    m = importlib.import_module(name='{}.{}'.format(prefix, config_name))
  File "D:\Anaconda3\envs\wkkk\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'configs.None'

Process finished with exit code 1

**Comment by Zhengpu-L** [comment]
> 运行train.py出现如下报错，请问是tensorboardx的问题吗 Traceback (most recent call last): File "D:\code\FreeNet-master\train.py", line 62, in train.run(config_path=args.config_path, File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\dp_train.py", line 29, in run cfg = config.import_config(config_path) File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\util\config.py", line 5, in import_config m = importlib.import_module(name='{}.{}'.format(prefix, config_name)) File "D:\Anaconda3\envs\wkkk\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 984, in _find_and_load_unlocked ModuleNotFoundError: No module named 'configs.None'
> 
> Process finished with exit code 1

不能直接运行py文件
要运行bash脚本，里面有config的路径

**Comment by Lingfeng805** [comment]
> > 运行train.py出现如下报错，请问是tensorboardx的问题吗 Traceback (most recent call last): File "D:\code\FreeNet-master\train.py", line 62, in train.run(config_path=args.config_path, File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\dp_train.py", line 29, in run cfg = config.import_config(config_path) File "D:\Anaconda3\envs\wkkk\lib\site-packages\simplecv\util\config.py", line 5, in import_config m = importlib.import_module(name='{}.{}'.format(prefix, config_name)) File "D:\Anaconda3\envs\wkkk\lib\importlib__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 984, in _find_and_load_unlocked ModuleNotFoundError: No module named 'configs.None'
> > Process finished with exit code 1
> 
> 不能直接运行py文件 要运行bash脚本，里面有config的路径

运行结束后，分类的结果图从哪里可以看到呀？
