### ISSUE TITLE
运行 train.py时报错

### ISSUE THREAD

**Issue by Zhengpu-L** [Z-Zheng/FreeNet#4]
Traceback (most recent call last):
  File "D:/论文代码书/代码/高光谱影像分类/全卷积FCN/FreeNet-master/train.py", line 60, in <module>
    train.run(config_path=args.config_path,
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\simplecv-0.3.4-py3.8.egg\simplecv\dp_train.py", line 29, in run
    cfg = config.import_config(config_path)
  File "D:\Anaconda\envs\Pytorch\lib\site-packages\simplecv-0.3.4-py3.8.egg\simplecv\util\config.py", line 5, in import_config
    m = importlib.import_module(name='{}.{}'.format(prefix, config_name))
  File "D:\Anaconda\envs\Pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'configs.None'

**Comment by Zhengpu-L** [comment]
**已解决**
不能直接运行train.py，需要运行三个后缀为sh的脚本文件
**所以问题的本质变成了在windows环境下运行作者的sh脚本**
在将数据按指定文件夹存放后，需要通过git bash 运行脚本文件
但是会出现2个问题，第一个问题是运行完成后，git bash窗口闪退
这个可以通过在脚本文件末尾加上以下代码解决
**echo 按任意键继续
read -n 1
echo 继续运行**
然后你会发现第二个问题，git bash无法找到train.py/无法找到数据
原因是作者的sh脚本都放在scripts子文件夹中，所以无法找到train.py和数据
把sh脚本复制到freenet-master主文件夹下，再运行即可
